on:
  # Disabled automatic triggers; run only when manually dispatched.
  workflow_dispatch:

name: Populate Build Cache

jobs:
  populate_build_cache:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit
